### ISSUE TITLE
Continuous integration tests

### ISSUE THREAD

**Issue by TomNicholas** [xarray-contrib/pint-xarray#5]
Need to set up some service to run the tests. 

Should also get some code style checking bots too (e.g. the PEP8 bot)

**Comment by jthielen** [comment]
It would also be great to incorporate test coverage and black/isort checks.

A related question is whether or not pint-xarray should follow Pint's lead in using [bors](https://bors.tech/), or just rely on GitHub's PR checks and merging? @hgrecco do you have any thoughts here?

**Comment by hgrecco** [comment]
Regarding linters. While I was reluctant at first, I am now very happy with black/isort/flake. I even using a pre commit hook using [https://pre-commit.com/](https://pre-commit.com/)

Content of : `.pre-commit-config.yaml1 
```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
```

Regarding bors (except the few days that it has not worked properly) I found it very useful. I allows me to: 
- Check everything with travis before merge
- Allow me to queue several PRs for merging
